/*====================================================
1) NATURAL JOIN
====================================================*/


-- Employees and Department names

SELECT EMP_NAME, DEPT_NAME
FROM EMPLOYEES
NATURAL JOIN DEPARTMENTS;



-- Orders with Customer names

SELECT ORDER_ID, CUSTOMER_NAME
FROM ORDERS
NATURAL JOIN CUSTOMERS;



-- Students and Courses

SELECT STUDENT_NAME, COURSE_NAME
FROM STUDENTS
NATURAL JOIN COURSES;



-- Projects and Employees

SELECT PROJECT_NAME, EMP_NAME
FROM PROJECTS
NATURAL JOIN EMPLOYEES;



-- Invoice details and Products

SELECT INVOICE_ID, PRODUCT_NAME
FROM INVOICES
NATURAL JOIN PRODUCTS;



-- Books and Authors

SELECT BOOK_TITLE, AUTHOR_NAME
FROM BOOKS
NATURAL JOIN AUTHORS;



-- Class schedules and Instructors

SELECT CLASS_DATE, INSTRUCTOR_NAME
FROM SCHEDULES
NATURAL JOIN INSTRUCTORS;



-- Suppliers and Products

SELECT SUPPLIER_NAME, PRODUCT_NAME
FROM SUPPLIERS
NATURAL JOIN PRODUCTS;



-- Customer Orders and Shipping

SELECT ORDER_ID, SHIPPING_DATE
FROM ORDERS
NATURAL JOIN SHIPPING;



-- Employees and Job Titles

SELECT EMP_NAME, JOB_TITLE
FROM EMPLOYEES
NATURAL JOIN JOBS;



/*====================================================
2) USING CLAUSE
====================================================*/


-- Employees and Departments

SELECT EMP_NAME, DEPT_NAME
FROM EMPLOYEES
JOIN DEPARTMENTS
USING(DEPARTMENT_ID);



-- Orders and Customers

SELECT ORDER_ID, CUSTOMER_NAME
FROM ORDERS
JOIN CUSTOMERS
USING(CUSTOMER_ID);



-- Products and Suppliers

SELECT PRODUCT_NAME, SUPPLIER_NAME
FROM PRODUCTS
JOIN SUPPLIERS
USING(SUPPLIER_ID);



-- Students and Enrollments

SELECT STUDENT_NAME, COURSE_TITLE
FROM STUDENTS
JOIN ENROLLMENTS
USING(STUDENT_ID);



-- Invoices and Products

SELECT INVOICE_NUMBER, PRODUCT_NAME
FROM INVOICES
JOIN PRODUCTS
USING(PRODUCT_ID);



-- Projects and Employees

SELECT PROJECT_NAME, EMP_NAME
FROM PROJECTS
JOIN EMPLOYEES
USING(PROJECT_ID);



-- Authors and Books

SELECT AUTHOR_NAME, BOOK_TITLE
FROM AUTHORS
JOIN BOOKS
USING(AUTHOR_ID);



-- Sales Orders and Employees

SELECT ORDER_ID, EMP_NAME
FROM SALES_ORDERS
JOIN EMPLOYEES
USING(EMPLOYEE_ID);



-- Course Schedule and Instructors

SELECT COURSE_NAME, INSTRUCTOR_NAME
FROM COURSE_SCHEDULE
JOIN INSTRUCTORS
USING(INSTRUCTOR_ID);



-- Transactions and Accounts

SELECT TRANSACTION_ID, ACCOUNT_NAME
FROM TRANSACTIONS
JOIN ACCOUNTS
USING(ACCOUNT_ID);



/*====================================================
3) TABLE ALIAS (AMBIGUOUS COLUMNS)
====================================================*/


-- Employee and Manager from same table

SELECT 
E.EMPLOYEE_ID,
E.NAME AS EMPLOYEE_NAME,
M.NAME AS MANAGER_NAME
FROM EMPLOYEES E
JOIN EMPLOYEES M
ON E.MANAGER_ID = M.EMPLOYEE_ID;



-- Customers and Salespersons

SELECT
C.NAME AS CUSTOMER_NAME,
E.NAME AS SALESPERSON_NAME
FROM CUSTOMERS C
JOIN EMPLOYEES E
ON C.SALESPERSON_ID = E.EMPLOYEE_ID;



-- Orders and Order Details

SELECT
O.ORDER_ID,
OD.PRODUCT_ID
FROM ORDERS O
JOIN ORDER_DETAILS OD
ON O.ORDER_ID = OD.ORDER_ID;



-- Students and Instructors

SELECT
S.NAME AS STUDENT_NAME,
I.NAME AS INSTRUCTOR_NAME
FROM STUDENTS S
JOIN INSTRUCTORS I
ON S.INSTRUCTOR_ID = I.INSTRUCTOR_ID;



-- Employee salaries and Department budgets

SELECT
E.NAME,
E.SALARY,
D.BUDGET
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;



-- Projects and Tasks

SELECT
P.NAME AS PROJECT_NAME,
T.NAME AS TASK_NAME
FROM PROJECTS P
JOIN TASKS T
ON P.PROJECT_ID = T.PROJECT_ID;



-- Courses and Exams dates

SELECT
C.COURSE_NAME,
C.EXAM_DATE AS COURSE_DATE,
E.EXAM_DATE AS EXAM_DATE
FROM COURSES C
JOIN EXAMS E
ON C.COURSE_ID = E.COURSE_ID;



-- Products and Categories

SELECT
P.NAME AS PRODUCT_NAME,
C.NAME AS CATEGORY_NAME
FROM PRODUCTS P
JOIN CATEGORIES C
ON P.CATEGORY_ID = C.CATEGORY_ID;



-- Books and Publishers

SELECT
B.TITLE AS BOOK_TITLE,
P.NAME AS PUBLISHER_NAME
FROM BOOKS B
JOIN PUBLISHERS P
ON B.PUBLISHER_ID = P.PUBLISHER_ID;



-- Employees and Department Location

SELECT
E.NAME AS EMPLOYEE_NAME,
D.LOCATION AS DEPARTMENT_LOCATION
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;