
-- Create Employees with age >= 18

CREATE TABLE EMPLOYEES
(
    ID NUMBER,
    NAME VARCHAR2(50),
    AGE NUMBER,

    CONSTRAINT CHK_AGE
    CHECK(AGE >= 18)
);


-- Salary between 3000 and 10000

CREATE TABLE STAFF
(
    ID NUMBER,
    NAME VARCHAR2(50),
    SALARY NUMBER,

    CONSTRAINT CHK_SALARY
    CHECK(SALARY BETWEEN 3000 AND 10000)
);


-- Add CHECK to existing Products

ALTER TABLE PRODUCTS
ADD CONSTRAINT CHK_PRICE
CHECK(PRICE > 0);


-- Students grade A-F

CREATE TABLE STUDENTS
(
    ID NUMBER,
    NAME VARCHAR2(50),
    GRADE CHAR(1),

    CONSTRAINT CHK_GRADE
    CHECK(GRADE IN ('A','B','C','D','E','F'))
);



/*====================================================
2) ADD CONSTRAINTS USING ALTER TABLE
====================================================*/


-- Add NOT NULL

ALTER TABLE CUSTOMERS
MODIFY EMAIL VARCHAR2(100) NOT NULL;


-- Add UNIQUE

ALTER TABLE USERS
ADD CONSTRAINT UK_USERNAME
UNIQUE(USERNAME);


-- Add FOREIGN KEY

ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDER_CUSTOMER
FOREIGN KEY(CUSTOMER_ID)
REFERENCES CUSTOMERS(ID);


-- Add CHECK

ALTER TABLE ACCOUNTS
ADD CONSTRAINT CHK_BALANCE
CHECK(BALANCE >= 0);


-- Add PRIMARY KEY

ALTER TABLE DEPARTMENTS
ADD CONSTRAINT PK_DEPARTMENT
PRIMARY KEY(DEPT_ID);



/*====================================================
3) DROP CONSTRAINTS
====================================================*/


-- Drop CHECK

ALTER TABLE EMPLOYEES
DROP CONSTRAINT CHK_SALARY;


-- Drop UNIQUE

ALTER TABLE USERS
DROP CONSTRAINT UK_EMAIL;


-- Drop PRIMARY KEY

ALTER TABLE PRODUCTS
DROP PRIMARY KEY;


-- Drop FOREIGN KEY

ALTER TABLE ORDERS
DROP CONSTRAINT FK_ORDER_CUSTOMER;


-- Remove NOT NULL

ALTER TABLE CONTACTS
MODIFY PHONE VARCHAR2(20) NULL;



/*====================================================
4) RENAME CONSTRAINTS (Oracle)
====================================================*/


ALTER TABLE STUDENTS
RENAME CONSTRAINT CHK_AGE
TO CHECK_MIN_AGE;


ALTER TABLE EMPLOYEES
RENAME CONSTRAINT FK_EMP_DEPT
TO FK_EMPLOYEE_DEPARTMENT;


ALTER TABLE USERS
RENAME CONSTRAINT USERS_PK
TO PK_USERS_ID;


ALTER TABLE USERS
RENAME CONSTRAINT USERNAME_UNIQUE
TO UK_USER_NAME;



-- SQL Server Rename

EXEC sp_rename 
'OLD_CONSTRAINT_NAME',
'NEW_CONSTRAINT_NAME';



-- PostgreSQL Rename

ALTER TABLE TABLE_NAME
RENAME CONSTRAINT OLD_NAME
TO NEW_NAME;



/*====================================================
5) DISABLE CONSTRAINTS
====================================================*/


-- Disable FOREIGN KEY

ALTER TABLE ORDERS
DISABLE CONSTRAINT FK_CUSTOMER_ORDER;


-- Disable CHECK

ALTER TABLE ACCOUNTS
DISABLE CONSTRAINT CHK_BALANCE;


-- Disable PRIMARY KEY

ALTER TABLE DEPARTMENTS
DISABLE PRIMARY KEY;


-- Disable constraint before bulk insert

ALTER TABLE TABLE_NAME
DISABLE CONSTRAINT CONSTRAINT_NAME;


-- After insert

ALTER TABLE TABLE_NAME
ENABLE CONSTRAINT CONSTRAINT_NAME;



/*====================================================
6) ENABLE CONSTRAINTS
====================================================*/


-- Enable FOREIGN KEY

ALTER TABLE ORDERS
ENABLE CONSTRAINT FK_CUSTOMER_ORDER;


-- Enable all constraints

ALTER TABLE PRODUCTS
ENABLE ALL CONSTRAINTS;


-- Enable CHECK

ALTER TABLE STAFF
ENABLE CONSTRAINT CHK_SALARY;


-- Enable PRIMARY KEY

ALTER TABLE DEPARTMENTS
ENABLE PRIMARY KEY;



-- Enable only if disabled (Oracle)

BEGIN
    EXECUTE IMMEDIATE
    'ALTER TABLE ORDERS ENABLE CONSTRAINT FK_CUSTOMER_ORDER';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/